### PR TITLE
Implementation of issue #137. GetOrganizationByName implemented on th…

### PR DESCRIPTION
**Pull request by jwynia**
…e specified interfaces and implementations.

### CODE REVIEW

**Comment by nbarbettini** [comment]
Looks great, thanks! :smile: 

I'll get this merged in today, and add integration tests before closing the original issue.

**Comment by nbarbettini** [comment]
Hey @jwynia - quick question: there might have been some miscommunication before. Are you needing to get an Organization by **name**, or **nameKey**? @dalelotts was discussing looking up by nameKey but your code looks up by name. (Name is just text, but nameKey is a guaranteed-unique identifier.)

Sorry for any confusion - I realize I mixed up the two properties myself in my pseudocode samples on the issue thread. Which one are you trying to grab here?

**Comment by jwynia** [comment]
The confusion was on our end because we're actually using the same value for name and nameKey. It should have been nameKey all of the way through.

**Comment by nbarbettini** [comment]
Closed via 22d0e5fc78c38de8d4140fe8de26b96656a7a2c9

**Pull request closed without merging**
